#!/bin/bash

echo "========================================="
echo "📋 VALIDADORES DO WARP ROUTE - SEPOLIA"
echo "========================================="
echo ""

WARP_ROUTE="0x224a4419D7FA69D3bEbAbce574c7c84B48D829b4"
WARP_ISM="0xb14FBB042272786B4Cb3af86207c20E4f865e0F3"

echo "📍 Contrato Warp Route:"
echo "   $WARP_ROUTE"
echo "   https://sepolia.etherscan.io/address/$WARP_ROUTE"
echo ""

echo "📍 ISM do Warp Route:"
echo "   $WARP_ISM"
echo "   https://sepolia.etherscan.io/address/$WARP_ISM"
echo ""

echo "========================================="
echo "🔍 COMO OBTER OS VALIDADORES"
echo "========================================="
echo ""
echo "Baseado no código do Hyperlane, o Warp Route herda de:"
echo "  TokenRouter → GasRouter → Router → MailboxClient"
echo ""
echo "O MailboxClient tem o método:"
echo "  interchainSecurityModule() → retorna IInterchainSecurityModule (address)"
echo ""
echo "O ISM (se for multisig) tem o método:"
echo "  validatorsAndThreshold(bytes message) → retorna (address[], uint8)"
echo ""
echo "OU se for StorageMultisigIsm, tem variável pública:"
echo "  validators() → retorna address[]"
echo "  threshold() → retorna uint8"
echo ""

echo "========================================="
echo "📝 MÉTODO 1: VIA ETHERSCAN (RECOMENDADO)"
echo "========================================="
echo ""
echo "1. Obter o ISM do Warp Route:"
echo "   https://sepolia.etherscan.io/address/$WARP_ROUTE#readContract"
echo "   → Execute: interchainSecurityModule()"
echo "   → Isso retorna o endereço do ISM"
echo ""
echo "2. Obter validadores do ISM:"
echo "   https://sepolia.etherscan.io/address/$WARP_ISM#readContract"
echo ""
echo "   Tente estes métodos (na ordem):"
echo ""
echo "   a) validators()"
echo "      → Se disponível, retorna array completo"
echo ""
echo "   b) validatorsAndThreshold(bytes)"
echo "      → Passe '0x' como parâmetro (mensagem vazia)"
echo "      → Retorna (address[], uint8)"
echo ""
echo "   c) threshold()"
echo "      → Retorna o threshold necessário"
echo ""

echo "========================================="
echo "📝 MÉTODO 2: VIA CAST (SE RPC FUNCIONAR)"
echo "========================================="
echo ""
echo "# 1. Obter ISM"
echo "cast call $WARP_ROUTE \"interchainSecurityModule()(address)\" --rpc-url <RPC>"
echo ""
echo "# 2. Obter validadores (se for StorageMultisigIsm)"
echo "cast call $WARP_ISM \"validators()(address[])\" --rpc-url <RPC>"
echo ""
echo "# 3. Obter threshold"
echo "cast call $WARP_ISM \"threshold()(uint8)\" --rpc-url <RPC>"
echo ""
echo "# 4. OU usar validatorsAndThreshold (se não tiver validators() público)"
echo "cast call $WARP_ISM \"validatorsAndThreshold(bytes)(address[],uint8)\" \"0x\" --rpc-url <RPC>"
echo ""

echo "========================================="
echo "💡 INFORMAÇÕES IMPORTANTES"
echo "========================================="
echo ""
echo "⚠️  Os validadores que aparecem nos logs do relayer:"
echo "    0x242d8a855a8c932dec51f7999ae7d1e48b10c95e"
echo "    0xf620f5e3d25a3ae848fec74bccae5de3edcd8796"
echo "    0x1f030345963c54ff8229720dd3a711c15c554aeb"
echo ""
echo "    São do ISM para mensagens BSC → Terra Classic,"
echo "    NÃO são os validadores do Warp Route Sepolia!"
echo ""
echo "✅ Para mensagens Sepolia → Terra Classic, você precisa"
echo "   dos validadores do ISM: $WARP_ISM"
echo ""
echo "========================================="

