#!/bin/bash

echo "========================================="
echo "📋 CONFIGURAÇÃO DO WARP ROUTE NO SOLANA"
echo "========================================="
echo ""

echo "✅ CONFIGURAÇÃO CORRETA (funcionando):"
echo ""
echo "📍 Warp Route Solana:"
echo "   Token Mint: 3yhG9dDHVX6K1duf8znEcaJcuTiKSLYvfBD4xy6akxfu"
echo "   Program ID: (Programa Sealevel do Hyperlane)"
echo ""

echo "🔧 ISM Configurado:"
echo "   → Tipo: DomainRoutingISM (tipo 1)"
echo "   → DomainRoutingISM.module(1325) = ISM do Terra Classic"
echo ""

echo "📝 Como funciona:"
echo ""
echo "   1. Mensagem enviada DO Solana PARA Terra Classic"
echo ""
echo "   2. Warp Route consulta o ISM configurado"
echo "      → ISM = DomainRoutingISM"
echo ""
echo "   3. DomainRoutingISM verifica o destino (domain 1325)"
echo "      → Retorna: ISM do Terra Classic"
echo ""
echo "   4. Relayer busca checkpoints dos validadores do Terra Classic"
echo "      → Validadores: 0x8804770d6a346210c0Fd011258FDf3Ab0a5bb0d0"
echo "      → Threshold: 1 de 1"
echo ""
echo "   5. Validadores do Terra Classic assinam os checkpoints"
echo ""
echo "   6. Mensagem é entregue no Terra Classic ✅"
echo ""

echo "========================================="
echo "🔍 DETALHES TÉCNICOS"
echo "========================================="
echo ""
echo "No Solana (Sealevel):"
echo "   • O Warp Route é um programa Sealevel"
echo "   • O ISM é armazenado no estado do programa"
echo "   • O ISM é DomainRoutingISM"
echo "   • DomainRoutingISM roteia baseado no domain de destino"
echo ""
echo "DomainRoutingISM:"
echo "   • É um ISM que roteia para diferentes ISMs baseado no domain"
echo "   • module(1325) retorna o ISM do Terra Classic"
echo "   • Isso permite usar validadores do Terra Classic para mensagens"
echo "     que vão para o Terra Classic"
echo ""

echo "========================================="
echo "📊 COMPARAÇÃO: SOLANA vs SEPOLIA"
echo "========================================="
echo ""

echo "✅ SOLANA (CORRETO):"
echo "   ISM = DomainRoutingISM"
echo "   DomainRoutingISM.module(1325) = ISM do Terra Classic"
echo "   Status: ✅ Funcionando (Terra Classic <> Solana ida e volta)"
echo ""

echo "❌ SEPOLIA (INCORRETO):"
echo "   ISM = MESSAGE_ID_MULTISIG (tipo 5)"
echo "   DomainRoutingISM.module(1325) = NÃO CONFIGURADO"
echo "   Status: ❌ Não funciona (mensagens não são entregues)"
echo ""

echo "========================================="
echo "💡 POR QUE FUNCIONA NO SOLANA?"
echo "========================================="
echo ""
echo "1. O ISM é DomainRoutingISM ✅"
echo "   → Permite rotear para diferentes ISMs por domain"
echo ""
echo "2. DomainRoutingISM está configurado para Terra Classic ✅"
echo "   → module(1325) retorna ISM do Terra Classic"
echo ""
echo "3. ISM do Terra Classic usa validadores do Terra Classic ✅"
echo "   → Validadores estão ativos e assinando"
echo ""
echo "4. Relayer busca checkpoints do Terra Classic ✅"
echo "   → Encontra checkpoints dos validadores corretos"
echo ""

echo "========================================="
echo "📝 SOLUÇÃO PARA SEPOLIA"
echo "========================================="
echo ""
echo "Para fazer o Sepolia funcionar como o Solana:"
echo ""
echo "1. Criar DomainRoutingISM no Sepolia"
echo "   → Usar DomainRoutingIsmFactory"
echo ""
echo "2. Configurar DomainRoutingISM para Terra Classic"
echo "   → DomainRoutingISM.set(1325, ISM_TERRA_CLASSIC)"
echo ""
echo "3. Configurar Warp Route para usar DomainRoutingISM"
echo "   → WarpRoute.setInterchainSecurityModule(DomainRoutingISM)"
echo ""
echo "📝 Use o script: ./configurar-ism-warp-sepolia-completo.sh"
echo ""

