#!/bin/bash

echo "========================================="
echo "📊 RESUMO FINAL - VALIDADORES CORRETOS"
echo "========================================="
echo ""

WARP_ROUTE="0x224a4419D7FA69D3bEbAbce574c7c84B48D829b4"
WARP_ISM="0xb14FBB042272786B4Cb3af86207c20E4f865e0F3"
VALIDATOR="0x8804770d6a346210c0Fd011258FDf3Ab0a5bb0d0"

echo "✅ CONFIRMAÇÕES:"
echo ""
echo "1. Warp Route (Sepolia):"
echo "   $WARP_ROUTE"
echo ""
echo "2. ISM do Warp Route:"
echo "   $WARP_ISM"
echo "   ✅ Confirmado associado ao Warp Route"
echo ""
echo "3. Validador do ISM:"
echo "   $VALIDATOR"
echo "   ✅ Confirmado: É do Terra Classic (domain 1325)"
echo ""
echo "4. Threshold: 1 de 1"
echo ""

echo "========================================="
echo "🔍 PROBLEMA IDENTIFICADO"
echo "========================================="
echo ""
echo "Para mensagens Sepolia → Terra Classic:"
echo ""
echo "   • Mensagem enviada DO Sepolia (origin: 11155111)"
echo "   • ISM no Terra Classic usa validadores do Terra Classic"
echo "   • Validador necessário: $VALIDATOR (Terra Classic)"
echo ""
echo "   ⚠️  O relayer busca checkpoints do domínio de ORIGEM (Sepolia)"
echo "      MAS o validador é do Terra Classic (destino)"
echo ""
echo "   💡 POSSÍVEIS SOLUÇÕES:"
echo ""
echo "   1. O validador do Terra Classic precisa anunciar no:"
echo "      → ValidatorAnnounce do TERRA CLASSIC"
echo "      → Contrato: 0xe604c0fcb8ddcf5eb2ca20bc73f6c5fd3d7eedae2ce0278dd41fb58cec5969fe"
echo ""
echo "   2. O relayer pode precisar buscar checkpoints do Terra Classic"
echo "      (não do Sepolia) se os validadores são do Terra Classic"
echo ""
echo "   3. Verificar configuração do checkpointSyncer no relayer"
echo "      para permitir buscar checkpoints de múltiplos domínios"
echo ""

echo "========================================="
echo "📝 PRÓXIMOS PASSOS"
echo "========================================="
echo ""
echo "1. Verificar se o validador está anunciado no Terra Classic:"
echo "   → Terra Finder: https://finder.terraclassic.community/testnet"
echo "   → Contrato: $VALIDATOR_ANNOUNCE_TERRA"
echo ""
echo "2. Verificar logs do relayer para ver de qual domínio"
echo "   ele está tentando buscar checkpoints"
echo ""
echo "3. Se necessário, configurar checkpointSyncer no relayer"
echo "   para buscar checkpoints do Terra Classic"
echo ""

echo "========================================="
echo "✅ Validador correto identificado!"
echo "========================================="

