#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║  IDENTIFICAR CONTA account_index: 5                                      ║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "Analisando os logs da simulação para identificar qual conta é account_index: 5"
echo ""

# Extrair informações dos logs
RECIPIENT="BirXd4QDxfq2vx9LGqgXXSgZrjT81rhoFGUbQRWDEf1j"
RELAYER_ADDRESS="C4jCuG3DjRdAnDJkJLXn711ShWDiat5nSTAZKYzPPCnY"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ANÁLISE DOS LOGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Dos logs da simulação, vejo que:"
echo ""
echo "1. A transação tenta criar uma Associated Token Account (ATA)"
echo "2. Recipient: $RECIPIENT"
echo "3. O erro ocorre em account_index: 5"
echo ""
echo "Em Solana, as contas em uma transação são indexadas assim:"
echo "  account_index: 0 = Signer principal (relayer)"
echo "  account_index: 1 = Program/Account sendo chamado"
echo "  account_index: 2-4 = Outras contas necessárias"
echo "  account_index: 5 = CONTA QUE ESTÁ FALTANDO SOL"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "POSSÍVEIS CAUSAS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "account_index: 5 provavelmente é:"
echo "  1. A Associated Token Account (ATA) sendo criada"
echo "  2. Ou uma conta derivada necessária para a transação"
echo ""
echo "O problema é que essa conta precisa de SOL para rent exemption,"
echo "mas o SOL está apenas no signer principal (account_index: 0)."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SOLUÇÃO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "O relayer deve transferir SOL do signer principal para a conta"
echo "derivada antes de criar a transação, OU a transação deve incluir"
echo "uma instrução para transferir SOL."
echo ""
echo "⚠️  Isso pode ser um bug no relayer ou uma configuração incorreta."
echo ""
echo "🔧 SOLUÇÕES A TENTAR:"
echo ""
echo "1. Adicionar MUITO mais SOL (5-10 SOL) para garantir que há suficiente"
echo "2. Verificar se há uma configuração do relayer para pré-funding de contas"
echo "3. Verificar se o relayer está usando a versão correta"
echo "4. Verificar se há uma forma de configurar o relayer para pré-criar ATAs"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AÇÃO IMEDIATA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1. Adicionar mais SOL (5-10 SOL recomendado):"
echo "   Faucet: https://faucet.solana.com/"
echo "   Endereço: $RELAYER_ADDRESS"
echo ""
echo "2. Reiniciar relayer completamente:"
echo "   cd teste-relayer"
echo "   docker compose -f docker-compose-relayer-only.yml stop relayer"
echo "   docker compose -f docker-compose-relayer-only.yml up -d relayer"
echo ""
echo "3. Monitorar logs por 10 minutos:"
echo "   docker logs -f hpl-relayer-testnet-local | grep -iE 'solana|insufficient|rent|error'"
echo ""

